# Generated by Django 6.0.7 on 2026-07-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=50)),
                ('target_year', models.IntegerField()),
                ('target_month', models.IntegerField()),
                ('forecast_volume', models.FloatField()),
                ('forecast_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommendScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_score', models.FloatField()),
                ('price_stability', models.FloatField()),
                ('price_risk', models.FloatField()),
                ('price_cheap', models.FloatField()),
                ('supply_stability', models.FloatField()),
                ('seasonality', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FishMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('is_frozen', models.BooleanField()),
                ('season', models.CharField(blank=True, max_length=100)),
                ('taste', models.TextField(blank=True)),
                ('cooking_method', models.CharField(blank=True, max_length=200)),
                ('nutrition', models.TextField(blank=True)),
                ('recipe_url', models.CharField(blank=True, max_length=200)),
                ('price_category', models.CharField(blank=True, max_length=20)),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('alternatives', models.ManyToManyField(blank=True, to='fish_web.fishmaster')),
            ],
        ),
    ]
