# Generated by Django 6.0.7 on 2026-08-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishmaster',
            name='season',
            field=models.JSONField(blank=True, default=list, verbose_name='旬の月リスト'),
        ),
    ]
