# Generated by Django 6.0.7 on 2026-08-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_web', '0002_alter_fishmaster_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendscore',
            name='target_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendscore',
            name='target_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
